#!/usr/bin/env python3
"""
Script to insert the Real Estate Lead Qualifier template into the database.
Run this script to create the hardcoded template for the demo.
"""

import asyncio
import sys
import os

# Add the parent directory to the path so we can import from api
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from api.db import db_client
from api.db.workflow_template_client import WorkflowTemplateClient


async def create_real_estate_template():
    """Create the Real Estate Lead Qualifier template."""
    
    template_client = WorkflowTemplateClient()
    
    # Check if template already exists
    existing = await template_client.get_workflow_template_by_name("Real Estate Lead Qualifier")
    if existing:
        print("Real Estate Lead Qualifier template already exists")
        return existing
    
    # Define the template structure as specified in the plan
    template_json = {
        "nodes": [
            {
                "id": "trigger-1",
                "type": "trigger",
                "data": {
                    "trigger_path": "<auto-generated-uuid>",
                    "label": "Incoming Call"
                }
            },
            {
                "id": "agent-1", 
                "type": "agent",
                "data": {
                    "system_prompt": "You are a professional real estate assistant. Your job is to:\n1. Greet the caller warmly\n2. Ask what type of property they're looking for\n3. Confirm their budget range\n4. Ask their preferred timeline\n5. Offer to book a viewing appointment\n\nBe conversational but efficient. If they ask something you don't know, offer to connect them with an agent.",
                    "first_message": "Hello! Thanks for calling {{agencyName}}. I'm here to help you find your perfect property. What type of property are you looking for today?",
                    "model": "gpt-4",
                    "voice": "alloy",
                    "temperature": 0.7
                }
            }
        ],
        "edges": [
            {
                "id": "e1",
                "source": "trigger-1",
                "target": "agent-1"
            }
        ]
    }
    
    template_context_variables = {
        "agencyName": "",
        "agentName": "", 
        "calendarLink": ""
    }
    
    try:
        template = await template_client.create_workflow_template(
            template_name="Real Estate Lead Qualifier",
            template_description="Qualifies incoming leads and books appointments",
            template_json={
                "workflow_definition": template_json,
                "template_context_variables": template_context_variables
            }
        )
        
        print(f"Created Real Estate Lead Qualifier template with ID: {template.id}")
        return template
        
    except Exception as e:
        print(f"Error creating template: {e}")
        raise


if __name__ == "__main__":
    asyncio.run(create_real_estate_template())
